# Generated by Django 2.1.2 on 2018-10-06 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={},
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
