# Generated by Django 2.1.2 on 2018-10-07 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20181006_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='time_info',
        ),
        migrations.AddField(
            model_name='subject',
            name='time_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.TimeInfo'),
        ),
    ]
