# Generated by Django 2.1.2 on 2018-10-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_auto_20181007_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeksubject',
            name='day_subjects',
            field=models.ManyToManyField(to='subjects.DaySubject'),
        ),
    ]
