# Generated by Django 2.1.2 on 2018-10-07 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_weeksubject_day_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeksubject',
            name='day_subjects',
        ),
        migrations.AlterField(
            model_name='daysubject',
            name='weekly_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_subjects', to='subjects.WeekSubject'),
        ),
    ]
