# Generated by Django 2.1.2 on 2018-10-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_auto_20181007_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daysubject',
            old_name='weekly_subject',
            new_name='week_subject',
        ),
    ]
